# Generated by Django 6.0.5 on 2026-05-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Amores Instituto', max_length=255)),
                ('descricao', models.TextField(default='O Instituto Amores é uma organização social sem fins lucrativos localizada no bairro Sapiranga, em Fortaleza–CE, dedicada à promoção de ações solidárias e ao fortalecimento da comunidade local.')),
                ('missao', models.TextField(default='Promover o bem-estar social por meio de ações solidárias, contribuindo para a melhoria da qualidade de vida das pessoas e fortalecendo os laços comunitários.')),
                ('visao', models.TextField(default='Ser referência em transformação social na comunidade, inspirando outras iniciativas e ampliando o alcance de nossas ações.')),
                ('valores', models.TextField(default='Solidariedade, Empatia, Respeito, Compromisso social, Transparência')),
                ('chave_pix', models.CharField(default='00.000.000/0001-00', max_length=255)),
                ('tipo_chave_pix', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'Email'), ('TELEFONE', 'Telefone'), ('ALEATORIA', 'Aleatória')], default='CNPJ', max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.CharField(default='Sapiranga, Fortaleza–CE', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instituição',
                'verbose_name_plural': 'Instituições',
            },
        ),
    ]
