# Generated by Django 6.0.5 on 2026-05-13 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Category description', verbose_name='description')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=120, unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, help_text='Category image', null=True, upload_to='categories/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active', verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order', verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Product description', verbose_name='description')),
                ('short_description', models.CharField(blank=True, help_text='Brief product description for listings', max_length=300, verbose_name='short description')),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Product cost price (for profit calculations)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cost price')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='discount percentage')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Current stock quantity', verbose_name='stock quantity')),
                ('min_stock_level', models.PositiveIntegerField(default=0, help_text='Minimum stock level before reorder', verbose_name='minimum stock level')),
                ('sku', models.CharField(blank=True, help_text='Stock Keeping Unit', max_length=100, unique=True, verbose_name='SKU')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='draft', help_text='Product status', max_length=20, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this product is featured', verbose_name='featured')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this product is available for purchase', verbose_name='available')),
                ('main_image', models.ImageField(blank=True, help_text='Main product image', null=True, upload_to='products/', verbose_name='main image')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the name', max_length=220, unique=True, verbose_name='slug')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=60, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160, verbose_name='meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
